CREATE TABLE Cuenta(
    id INTEGER PRIMARY KEY
    usuario TEXT NOT NULL,
    contraseña TEXT NOT NULL,
    idSitioWeb INTEGER NOT NULL,
);

CREATE TABLE SitioWeb(
    id INTEGER PRIMARY KEY
    nombre TEXT NOT NULL,
);

INSERT INTO SitioWeb VALUES (Pepe)
INSERT INTO SitioWeb VALUES (Pepe)
INSERT INTO SitioWeb VALUES (Pepe)
INSERT INTO SitioWeb VALUES (Pepe)
INSERT INTO SitioWeb VALUES (Pepe)